# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20180611_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='aticle',
            name='stick',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
