# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_aticle_stick'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aticle',
            table='article',
        ),
    ]
