# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20180611_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aticle',
            new_name='Article',
        ),
    ]
