# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=32)),
                ('url', models.URLField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, default='boardavatars/default.png', null=True, upload_to='boardavatars/')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MessageBoard.Message')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
