# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True),
        ),
    ]
