# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_auto_20180613_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
